version: "3"
services:
  oxigraph:
    image: oxigraph/oxigraph:latest
    volumes:
      - ./oxigraph:/data
    ports:
      - "7878:7878"
  client:
    image: node:16
    volumes:
      - ./client:/app
    working_dir: /app
    ports:
      - "3000:3000"
    command: "yarn run dev"
  webserver:
    image: nginx:latest
    volumes:
      - ./nginx/static:/app/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    working_dir: /app
    ports:
      - "8080:8080"
